language: java
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean deploy --settings target/travis/settings.xml; 
else 
    mvn clean verify --settings target/travis/settings.xml;
fi"

jdk:
  - openjdk6

# whitelist
branches:
  only:
    - develop

env:
  global:
    - secure: "HDnwv4zR6yCDVVUROKw3oHmXFfBniaKVB/iX03knGemRGqG5yc6k8E6d/td5\naF3OPb+ymBRj6R+Ksxl6X7LYNMVTafIwJl1MKweDnGKkF0GpwC8JocUPxuyh\n/h9IrTYbJKtk/Sle1oYoQcmN7sK93TmrtUAO5qWYkRllL9kEGlk="
    - secure: "mnXSFedxwTETOFH7dXGZwYD7X9IfLAUPvZ97VvHpQp7lkoaq2/u+Z66XNNUW\nfFRr1z50EKJpo1ET1cQIaizGGuolARpNlLEmBP1M202LEysV/MERi/wLIGml\nz1Zrlr4wc8UO/b+1WGW3oCi6F0y8zv1TWGd+yWlHoLh4+XiNZLQ="